apiVersion: xl-release/v1beta1
kind: Templates
spec:
- name: E-COMMERCE
  type: xlrelease.Folder
  children:
  - name: e-commerce
    type: xlrelease.Release
    description: |
      This XL Release template shows how to deploy and undeploy an application, based on microservices architecture, to AWS ECS using XL Deploy.
    tags:
    - e-commerce
    - ECS
    ### to be changed to secrets,plain text for now
    scriptUsername: "admin"
    scriptUserPassword: "admin"
    variables:
    - key: "ECSClusterName"
      type: "xlrelease.StringVariable"
      requiresValue: "false"
      showOnReleaseStart: "false"
    - key: "ECSExecutionRoleArn"
      type: "xlrelease.StringVariable"
      requiresValue: "false"
      showOnReleaseStart: "false"
    - key: "ECSClusterArn"
      type: "xlrelease.StringVariable"
      requiresValue: "false"
      showOnReleaseStart: "false"
    phases:
    - name: Provision Infrastructure
      color: '#ff9e3b'
      type: xlrelease.Phase
      tasks:
      - name: Provision ecommerce product in service catalog
        type: xldeploy.Deploy
        server: XL Deploy
        deploymentPackage: ecommerce-monolith/ecommerce-sc/1.0
        deploymentEnvironment: Environments/AWS-Service-Catalog
      - name: Update Infra Items
        type: xlrelease.SequentialGroup
        tasks:
        - name: Get OutputVariables
          type: xld.GetCITask
          server: XL Deploy
          ciID: Infrastructure/aws/Service-Catalog-EU-WEST-1/ecommerce-infra
          accept: "json"
          variableMapping:
             pythonScript.response: "${outputs}"
        - name: Store OutputVariables to XLR variables
          type: xlrelease.ScriptTask
          script: |
            import json
            for k, v in json.loads(releaseVariables['outputs'])['outputVariables'].iteritems():
                releaseVariables[k] = v
        - name: Update CLuster name on ECS cluster
          type: xld.UpdateCIProperty
          server: XL Deploy
          ciID: Infrastructure/aws/ecommerceMonolithCluster
          ciProperty: clusterName
          propertyValue: "${ECSClusterName}"
        - name: Update CLuster region on ECS cluster
          type: xld.UpdateCIProperty
          server: XL Deploy
          ciID: Infrastructure/aws/ecommerceMonolithCluster
          ciProperty: region
          propertyValue: "eu-west-1"
        - name: Update CLuster ARN on ECS cluster
          type: xld.UpdateCIProperty
          server: XL Deploy
          ciID: Infrastructure/aws/ecommerceMonolithCluster
          ciProperty: clusterArn
          propertyValue: "${ECSClusterArn}"
        - name: Update ECS Dictionary
          type: xld.UpdateCIProperty
          server: XL Deploy
          ciID: Environments/ECS Dictionary
          ciProperty: entries
          propertyValue: |
                {"ECS_EXECUTION_ROLE":"${ECSExecutionRoleArn}","region":"eu-west-1"}
    - name: Deploy e-commerce application
      type: xlrelease.Phase
      tasks:
      - name: Deploy store app
        type: xldeploy.Deploy
        server: XL Deploy
        deploymentPackage: ecommerce-monolith/ecommerce-app-service/v1.0
        deploymentEnvironment: Environments/ECS
    - name: Test
      type: xlrelease.Phase
      tasks:
    - name: Undeploy Application
      type: xlrelease.Phase
      tasks:
      - name: Undeploy store app
        type: xldeploy.Undeploy
        server: XL Deploy
        deployedApplication: Environments/ECS/ecommerce-app-service
    - name: Deprovision Infrastracture
      type: xlrelease.Phase
      tasks:
      - name: ecommerece product in service catalog
        type: xldeploy.Undeploy
        server: XL Deploy
        deployedApplication: Environments/AWS-Service-Catalog/ecommerce-sc
